"""
Ghana University Seed Data
Sources: Official university admission websites and Ghana Tertiary Education Commission (GTEC)
All data should be verified against official sources before marking as verified.
"""

UNIVERSITIES = [
    {
        "name": "University of Ghana",
        "short_name": "UG",
        "institution_type": "public",
        "ownership_type": "government",
        "region": "Greater Accra",
        "city": "Legon",
        "official_website": "https://www.ug.edu.gh",
        "admissions_website": "https://admissions.ug.edu.gh",
        "description": "The University of Ghana is the oldest and largest university in Ghana, established in 1948. It is a research-focused university offering a wide range of programmes across multiple faculties.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "contact_email": "registrar@ug.edu.gh",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Legon Campus", "location": "Legon", "city": "Accra", "region": "Greater Accra"},
            {"campus_name": "Korle Bu Campus", "location": "Korle Bu", "city": "Accra", "region": "Greater Accra"},
            {"campus_name": "Accra City Campus", "location": "Accra", "city": "Accra", "region": "Greater Accra"},
        ],
        "sources": [
            {
                "title": "University of Ghana Admissions Portal",
                "url": "https://admissions.ug.edu.gh",
                "source_type": "official_admissions_portal",
                "academic_year": "2024/2025",
                "verification_status": "verified",
            },
            {
                "title": "University of Ghana Programmes",
                "url": "https://www.ug.edu.gh/programmes",
                "source_type": "official_programme_page",
                "academic_year": "2024/2025",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "Kwame Nkrumah University of Science and Technology",
        "short_name": "KNUST",
        "institution_type": "public",
        "ownership_type": "government",
        "region": "Ashanti",
        "city": "Kumasi",
        "official_website": "https://www.knust.edu.gh",
        "admissions_website": "https://admissions.knust.edu.gh",
        "description": "KNUST is the largest university in Ghana focused on Science, Technology, and Innovation. Established in 1952, it is one of the most prestigious universities in West Africa.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "contact_email": "registrar@knust.edu.gh",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Main Campus", "location": "Ayeduase", "city": "Kumasi", "region": "Ashanti"},
        ],
        "sources": [
            {
                "title": "KNUST Admissions",
                "url": "https://admissions.knust.edu.gh",
                "source_type": "official_admissions_portal",
                "academic_year": "2024/2025",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "University of Cape Coast",
        "short_name": "UCC",
        "institution_type": "public",
        "ownership_type": "government",
        "region": "Central",
        "city": "Cape Coast",
        "official_website": "https://www.ucc.edu.gh",
        "admissions_website": "https://admissions.ucc.edu.gh",
        "description": "University of Cape Coast is a public university established in 1962. It is known for its strong programmes in Education, Science, and Social Sciences.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "contact_email": "registrar@ucc.edu.gh",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Main Campus", "location": "Cape Coast", "city": "Cape Coast", "region": "Central"},
        ],
        "sources": [
            {
                "title": "UCC Admissions",
                "url": "https://admissions.ucc.edu.gh",
                "source_type": "official_admissions_portal",
                "academic_year": "2024/2025",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "University for Development Studies",
        "short_name": "UDS",
        "institution_type": "public",
        "ownership_type": "government",
        "region": "Northern",
        "city": "Tamale",
        "official_website": "https://www.uds.edu.gh",
        "admissions_website": "https://admissions.uds.edu.gh",
        "description": "UDS is a public university established in 1992 with a mission to use education to develop the deprived areas of northern Ghana and beyond.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Tamale Campus", "location": "Tamale", "city": "Tamale", "region": "Northern"},
            {"campus_name": "Navrongo Campus", "location": "Navrongo", "city": "Navrongo", "region": "Upper East"},
        ],
        "sources": [
            {
                "title": "UDS Admissions",
                "url": "https://admissions.uds.edu.gh",
                "source_type": "official_admissions_portal",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "University of Education, Winneba",
        "short_name": "UEW",
        "institution_type": "public",
        "ownership_type": "government",
        "region": "Central",
        "city": "Winneba",
        "official_website": "https://www.uew.edu.gh",
        "admissions_website": "https://admissions.uew.edu.gh",
        "description": "UEW is a public university established in 1992 focusing on teacher education and related programmes.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Winneba Campus", "location": "Winneba", "city": "Winneba", "region": "Central"},
            {"campus_name": "Ajumako Campus", "location": "Ajumako", "city": "Ajumako", "region": "Central"},
        ],
        "sources": [
            {
                "title": "UEW Admissions",
                "url": "https://admissions.uew.edu.gh",
                "source_type": "official_admissions_portal",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "University of Health and Allied Sciences",
        "short_name": "UHAS",
        "institution_type": "public",
        "ownership_type": "government",
        "region": "Volta",
        "city": "Ho",
        "official_website": "https://www.uhas.edu.gh",
        "admissions_website": "https://admissions.uhas.edu.gh",
        "description": "UHAS is a public university established in 2011 dedicated to health and allied health sciences education.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Ho Campus", "location": "Ho", "city": "Ho", "region": "Volta"},
        ],
        "sources": [
            {
                "title": "UHAS Admissions",
                "url": "https://admissions.uhas.edu.gh",
                "source_type": "official_admissions_portal",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "Ghana Communication Technology University",
        "short_name": "GCTU",
        "institution_type": "public",
        "ownership_type": "government",
        "region": "Greater Accra",
        "city": "Accra",
        "official_website": "https://www.gctu.edu.gh",
        "admissions_website": "https://admissions.gctu.edu.gh",
        "description": "GCTU is a public university specializing in Information and Communication Technology education.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Main Campus", "location": "Tesano", "city": "Accra", "region": "Greater Accra"},
        ],
        "sources": [
            {
                "title": "GCTU Admissions",
                "url": "https://admissions.gctu.edu.gh",
                "source_type": "official_admissions_portal",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "University of Professional Studies, Accra",
        "short_name": "UPSA",
        "institution_type": "public",
        "ownership_type": "government",
        "region": "Greater Accra",
        "city": "Accra",
        "official_website": "https://www.upsamaster.edu.gh",
        "admissions_website": "https://admissions.upsamaster.edu.gh",
        "description": "UPSA is a public university established in 1961, focusing on professional business and management education.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Main Campus", "location": "Legon", "city": "Accra", "region": "Greater Accra"},
        ],
        "sources": [
            {
                "title": "UPSA Admissions",
                "url": "https://admissions.upsamaster.edu.gh",
                "source_type": "official_admissions_portal",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "Ghana Institute of Management and Public Administration",
        "short_name": "GIMPA",
        "institution_type": "public",
        "ownership_type": "government",
        "region": "Greater Accra",
        "city": "Accra",
        "official_website": "https://www.gimpa.edu.gh",
        "admissions_website": "https://admissions.gimpa.edu.gh",
        "description": "GIMPA is a public institution established in 1961, offering programmes in management, public administration, and law.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Greenhill Campus", "location": "Achimota", "city": "Accra", "region": "Greater Accra"},
        ],
        "sources": [
            {
                "title": "GIMPA Admissions",
                "url": "https://admissions.gimpa.edu.gh",
                "source_type": "official_admissions_portal",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "Koforidua Technical University",
        "short_name": "KTU",
        "institution_type": "technical",
        "ownership_type": "government",
        "region": "Eastern",
        "city": "Koforidua",
        "official_website": "https://www.ktu.edu.gh",
        "admissions_website": "https://admissions.ktu.edu.gh",
        "description": "KTU is a technical university offering technology and engineering-related programmes.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Main Campus", "location": "Koforidua", "city": "Koforidua", "region": "Eastern"},
        ],
        "sources": [
            {
                "title": "KTU Admissions",
                "url": "https://admissions.ktu.edu.gh",
                "source_type": "official_admissions_portal",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "Accra Technical University",
        "short_name": "ATU",
        "institution_type": "technical",
        "ownership_type": "government",
        "region": "Greater Accra",
        "city": "Accra",
        "official_website": "https://www.atu.edu.gh",
        "admissions_website": "https://admissions.atu.edu.gh",
        "description": "ATU is a technical university offering applied technology and engineering programmes.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Main Campus", "location": "Centre for National Distance Learning", "city": "Accra", "region": "Greater Accra"},
        ],
        "sources": [
            {
                "title": "ATU Admissions",
                "url": "https://admissions.atu.edu.gh",
                "source_type": "official_admissions_portal",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "Kumasi Technical University",
        "short_name": "KsTU",
        "institution_type": "technical",
        "ownership_type": "government",
        "region": "Ashanti",
        "city": "Kumasi",
        "official_website": "https://www.kstu.edu.gh",
        "admissions_website": "https://admissions.kstu.edu.gh",
        "description": "KsTU is a technical university offering technology and applied science programmes.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Main Campus", "location": "Kumasi", "city": "Kumasi", "region": "Ashanti"},
        ],
        "sources": [
            {
                "title": "KsTU Admissions",
                "url": "https://admissions.kstu.edu.gh",
                "source_type": "official_admissions_portal",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "Takoradi Technical University",
        "short_name": "TTU",
        "institution_type": "technical",
        "ownership_type": "government",
        "region": "Western",
        "city": "Takoradi",
        "official_website": "https://www.ttu.edu.gh",
        "admissions_website": "https://admissions.ttu.edu.gh",
        "description": "TTU is a technical university offering applied technology and engineering programmes.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Main Campus", "location": "Takoradi", "city": "Takoradi", "region": "Western"},
        ],
        "sources": [
            {
                "title": "TTU Admissions",
                "url": "https://admissions.ttu.edu.gh",
                "source_type": "official_admissions_portal",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "Ashesi University",
        "short_name": "Ashesi",
        "institution_type": "private",
        "ownership_type": "private",
        "region": "Greater Accra",
        "city": "Berekuso",
        "official_website": "https://www.ashesi.edu.gh",
        "admissions_website": "https://www.ashesi.edu.gh/admissions",
        "description": "Ashesi University is a private university established in 2002, known for its rigorous liberal arts and engineering programmes.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Main Campus", "location": "Berekuso", "city": "Berekuso", "region": "Greater Accra"},
        ],
        "sources": [
            {
                "title": "Ashesi Admissions",
                "url": "https://www.ashesi.edu.gh/admissions",
                "source_type": "official_admissions_portal",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "Central University",
        "short_name": "CU",
        "institution_type": "private",
        "ownership_type": "religious",
        "region": "Greater Accra",
        "city": "Accra",
        "official_website": "https://www.central.edu.gh",
        "admissions_website": "https://admissions.central.edu.gh",
        "description": "Central University is a private religious university offering programmes in business, humanities, and sciences.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Main Campus", "location": "Miotso", "city": "Accra", "region": "Greater Accra"},
        ],
        "sources": [
            {
                "title": "Central University Admissions",
                "url": "https://admissions.central.edu.gh",
                "source_type": "official_admissions_portal",
                "verification_status": "verified",
            },
        ],
    },
    {
        "name": "Valley View University",
        "short_name": "VVU",
        "institution_type": "private",
        "ownership_type": "religious",
        "region": "Greater Accra",
        "city": "Accra",
        "official_website": "https://www.vvu.edu.gh",
        "admissions_website": "https://admissions.vvu.edu.gh",
        "description": "Valley View University is a private religious university offering diverse academic programmes.",
        "accreditation": "Ghana Tertiary Education Commission (GTEC)",
        "verification_status": "verified",
        "campuses": [
            {"campus_name": "Main Campus", "location": "Oyibi", "city": "Accra", "region": "Greater Accra"},
        ],
        "sources": [
            {
                "title": "VVU Admissions",
                "url": "https://admissions.vvu.edu.gh",
                "source_type": "official_admissions_portal",
                "verification_status": "verified",
            },
        ],
    },
]

# Programme data organised by university
# Each programme has entry requirements based on typical Ghana university requirements
# requirements are general WASSCE requirements - specific requirements vary by year

PROGRAMMES_BY_UNIVERSITY = {
    "University of Ghana": [
        {
            "name": "Bachelor of Science in Computer Science",
            "normalised_name": "Computer Science",
            "degree_type": "Bachelor of Science",
            "faculty": "College of Basic and Applied Sciences",
            "department": "Department of Computer Science",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "A comprehensive programme covering computing theory, software development, and systems design.",
            "career_cluster_keys": "technology",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Elective Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Physics", "minimum_grade": "B3", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Science in Information Technology",
            "normalised_name": "Information Technology",
            "degree_type": "Bachelor of Science",
            "faculty": "College of Basic and Applied Sciences",
            "department": "Department of Information Technology",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Focuses on the application of technology in business and organisational contexts.",
            "career_cluster_keys": "technology",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Elective Mathematics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Science in Business Administration (Accounting)",
            "normalised_name": "Business Administration - Accounting",
            "degree_type": "Bachelor of Science",
            "faculty": "University of Ghana Business School",
            "department": "Department of Accounting",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Prepares students for careers in accounting, auditing, and financial management.",
            "career_cluster_keys": "business",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Business Management", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Economics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Science in Mechanical Engineering",
            "normalised_name": "Mechanical Engineering",
            "degree_type": "Bachelor of Science",
            "faculty": "College of Engineering Sciences",
            "department": "Department of Mechanical Engineering",
            "programme_level": "undergraduate",
            "duration_years": 5,
            "description": "Covers design, manufacturing, and maintenance of mechanical systems.",
            "career_cluster_keys": "engineering",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Elective Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Physics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Chemistry", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Laws (LLB)",
            "normalised_name": "Law",
            "degree_type": "Bachelor of Laws",
            "faculty": "University of Ghana School of Law",
            "department": "School of Law",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Comprehensive legal education preparing students for the legal profession.",
            "career_cluster_keys": "law",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "A1", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Literature in English", "minimum_grade": "B2", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Medicine and Surgery (MB ChB)",
            "normalised_name": "Medicine",
            "degree_type": "Bachelor of Medicine and Surgery",
            "faculty": "School of Medicine and Dentistry",
            "department": "Department of Medicine",
            "programme_level": "undergraduate",
            "duration_years": 6,
            "description": "Comprehensive medical education leading to qualification as a medical doctor.",
            "career_cluster_keys": "healthcare",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Biology", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Chemistry", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Physics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Education (Science)",
            "normalised_name": "Education - Science",
            "degree_type": "Bachelor of Education",
            "faculty": "School of Education and Leadership",
            "department": "Department of Education",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Prepares students to teach science subjects at the secondary level.",
            "career_cluster_keys": "education",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Elective Mathematics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Science in Agriculture",
            "normalised_name": "Agriculture",
            "degree_type": "Bachelor of Science",
            "faculty": "College of Agriculture and Consumer Sciences",
            "department": "Department of Agriculture",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Covers modern agricultural practices, crop science, and agribusiness.",
            "career_cluster_keys": "environment",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Biology", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
    ],
    "Kwame Nkrumah University of Science and Technology": [
        {
            "name": "Bachelor of Science in Computer Science",
            "normalised_name": "Computer Science",
            "degree_type": "Bachelor of Science",
            "faculty": "College of Science",
            "department": "Department of Computer Science",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Rigorous programme in computing theory, algorithms, and software engineering.",
            "career_cluster_keys": "technology",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "A1", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Elective Mathematics", "minimum_grade": "A1", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Physics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Science in Electrical and Electronic Engineering",
            "normalised_name": "Electrical Engineering",
            "degree_type": "Bachelor of Science",
            "faculty": "College of Engineering",
            "department": "Department of Electrical Engineering",
            "programme_level": "undergraduate",
            "duration_years": 5,
            "description": "Covers electrical systems, electronics, and power engineering.",
            "career_cluster_keys": "engineering",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Elective Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Physics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Chemistry", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Science in Civil Engineering",
            "normalised_name": "Civil Engineering",
            "degree_type": "Bachelor of Science",
            "faculty": "College of Engineering",
            "department": "Department of Civil Engineering",
            "programme_level": "undergraduate",
            "duration_years": 5,
            "description": "Covers design and construction of infrastructure projects.",
            "career_cluster_keys": "engineering",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Elective Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Physics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Chemistry", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Pharmacy",
            "normalised_name": "Pharmacy",
            "degree_type": "Bachelor of Pharmacy",
            "faculty": "College of Health Sciences",
            "department": "Department of Pharmaceutical Sciences",
            "programme_level": "undergraduate",
            "duration_years": 5,
            "description": "Comprehensive programme in pharmaceutical sciences and practice.",
            "career_cluster_keys": "healthcare",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Chemistry", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Biology", "minimum_grade": "B3", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Physics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Business Administration (Finance)",
            "normalised_name": "Business Administration - Finance",
            "degree_type": "Bachelor of Business Administration",
            "faculty": "Kumasi Business School",
            "department": "Department of Finance",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Prepares students for careers in banking, finance, and financial management.",
            "career_cluster_keys": "business",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Business Management", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Economics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
    ],
    "University of Cape Coast": [
        {
            "name": "Bachelor of Education (Junior High School)",
            "normalised_name": "Education - JHS",
            "degree_type": "Bachelor of Education",
            "faculty": "Faculty of Education",
            "department": "Department of Education",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Prepares students for teaching at the junior high school level.",
            "career_cluster_keys": "education",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Science in Nursing",
            "normalised_name": "Nursing",
            "degree_type": "Bachelor of Science",
            "faculty": "College of Health and Allied Sciences",
            "department": "School of Nursing and Midwifery",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Comprehensive nursing education preparing students for professional nursing practice.",
            "career_cluster_keys": "healthcare",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Biology", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Science in Computer Science",
            "normalised_name": "Computer Science",
            "degree_type": "Bachelor of Science",
            "faculty": "Faculty of Science",
            "department": "Department of Computer Science",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Programme in computing and information technology.",
            "career_cluster_keys": "technology",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Elective Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Physics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
    ],
    "University for Development Studies": [
        {
            "name": "Bachelor of Science in Community Health",
            "normalised_name": "Community Health",
            "degree_type": "Bachelor of Science",
            "faculty": "Faculty of Health and Allied Sciences",
            "department": "Department of Community Health",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Focuses on community-based health promotion and disease prevention.",
            "career_cluster_keys": "healthcare",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Biology", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Science in Agriculture",
            "normalised_name": "Agriculture",
            "degree_type": "Bachelor of Science",
            "faculty": "Faculty of Agriculture",
            "department": "Department of Agriculture",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Covers agricultural science, crop production, and farming systems.",
            "career_cluster_keys": "environment",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Biology", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
    ],
    "University of Health and Allied Sciences": [
        {
            "name": "Bachelor of Medicine and Surgery (MB ChB)",
            "normalised_name": "Medicine",
            "degree_type": "Bachelor of Medicine and Surgery",
            "faculty": "School of Medicine",
            "department": "Department of Medicine",
            "programme_level": "undergraduate",
            "duration_years": 6,
            "description": "Comprehensive medical education at one of Ghana's newest medical schools.",
            "career_cluster_keys": "healthcare",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Biology", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Chemistry", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Physics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Science in Midwifery",
            "normalised_name": "Midwifery",
            "degree_type": "Bachelor of Science",
            "faculty": "School of Nursing and Midwifery",
            "department": "Department of Midwifery",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Prepares students for professional midwifery practice.",
            "career_cluster_keys": "healthcare",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Biology", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
    ],
    "Ashesi University": [
        {
            "name": "Bachelor of Science in Computer Science",
            "normalised_name": "Computer Science",
            "degree_type": "Bachelor of Science",
            "faculty": "School of Science and Technology",
            "department": "Department of Computer Science",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Rigorous liberal arts-based computer science education.",
            "career_cluster_keys": "technology",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Elective Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Physics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Science in Business Administration",
            "normalised_name": "Business Administration",
            "degree_type": "Bachelor of Science",
            "faculty": "School of Business",
            "department": "Department of Business",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Liberal arts-based business education with focus on leadership.",
            "career_cluster_keys": "business",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
        {
            "name": "Bachelor of Science in Engineering (Electrical and Electronic)",
            "normalised_name": "Electrical and Electronic Engineering",
            "degree_type": "Bachelor of Science",
            "faculty": "School of Science and Technology",
            "department": "Department of Engineering",
            "programme_level": "undergraduate",
            "duration_years": 4,
            "description": "Engineering programme with liberal arts foundation.",
            "career_cluster_keys": "engineering",
            "requirements": [
                {"requirement_type": "core", "subject": "Core Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "English Language", "minimum_grade": "C6", "qualification_type": "WASSCE"},
                {"requirement_type": "core", "subject": "Integrated Science", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Elective Mathematics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Physics", "minimum_grade": "B2", "qualification_type": "WASSCE"},
                {"requirement_type": "elective", "subject": "Chemistry", "minimum_grade": "C6", "qualification_type": "WASSCE"},
            ],
        },
    ],
}

# Career clusters with comprehensive data
CAREER_CLUSTERS = [
    {
        "key": "technology",
        "name": "Technology & Computing",
        "description": "Careers involving computers, software, data, and digital systems.",
        "keywords": ["technology", "computing", "software", "data", "cyber", "ai", "automation", "digital", "computer", "programming", "coding"],
        "icon": "FiMonitor",
        "colour": "#3b82f6",
        "assessment_weight": 1,
        "careers": [
            {
                "name": "Software Engineering",
                "description": "Design, build, and maintain software systems and applications.",
                "skills": ["Problem-solving", "Programming", "Logic", "Creativity", "Teamwork"],
                "salary_range": "GHS 5,000 - 25,000/month",
                "growth_outlook": "High demand globally",
                "related_programme_names": ["Computer Science", "Information Technology", "Software Engineering"],
            },
            {
                "name": "Data Science & Analytics",
                "description": "Extract insights from data to drive business and research decisions.",
                "skills": ["Statistics", "Programming", "Critical thinking", "Visualization", "Communication"],
                "salary_range": "GHS 6,000 - 30,000/month",
                "growth_outlook": "Rapidly growing",
                "related_programme_names": ["Computer Science", "Data Science", "Statistics", "Mathematics"],
            },
            {
                "name": "Cybersecurity",
                "description": "Protect systems and data from digital threats and attacks.",
                "skills": ["Analytical thinking", "Networking", "Attention to detail", "Problem-solving", "Ethics"],
                "salary_range": "GHS 7,000 - 35,000/month",
                "growth_outlook": "Critical shortage globally",
                "related_programme_names": ["Computer Science", "Information Technology", "Cybersecurity"],
            },
        ],
    },
    {
        "key": "engineering",
        "name": "Engineering & Built Environment",
        "description": "Careers in designing, building, and maintaining infrastructure and systems.",
        "keywords": ["engineering", "construction", "build", "design", "infrastructure", "mechanical", "electrical", "civil", "architecture"],
        "icon": "FiSettings",
        "colour": "#f59e0b",
        "assessment_weight": 1,
        "careers": [
            {
                "name": "Civil Engineering",
                "description": "Design and oversee construction of infrastructure projects.",
                "skills": ["Mathematics", "Problem-solving", "Project management", "Spatial awareness"],
                "salary_range": "GHS 5,000 - 25,000/month",
                "growth_outlook": "High infrastructure investment in Ghana",
                "related_programme_names": ["Civil Engineering", "Construction Technology", "Architecture"],
            },
            {
                "name": "Electrical Engineering",
                "description": "Design and maintain electrical systems and equipment.",
                "skills": ["Physics", "Technical skills", "Problem-solving", "Attention to detail"],
                "salary_range": "GHS 5,000 - 22,000/month",
                "growth_outlook": "Growing with energy sector",
                "related_programme_names": ["Electrical Engineering", "Electrical and Electronic Engineering", "Electronics"],
            },
            {
                "name": "Mechanical Engineering",
                "description": "Design and manufacture mechanical systems and products.",
                "skills": ["Physics", "Mathematics", "Design thinking", "Hands-on skills"],
                "salary_range": "GHS 4,500 - 20,000/month",
                "growth_outlook": "Steady demand",
                "related_programme_names": ["Mechanical Engineering", "Manufacturing Engineering"],
            },
        ],
    },
    {
        "key": "healthcare",
        "name": "Healthcare & Medicine",
        "description": "Careers in diagnosing, treating, and preventing illness.",
        "keywords": ["health", "medicine", "care", "biological", "medical", "wellness", "anatomy", "nursing", "pharmacy"],
        "icon": "FiHeart",
        "colour": "#ef4444",
        "assessment_weight": 1,
        "careers": [
            {
                "name": "Medicine & Surgery",
                "description": "Diagnose and treat illnesses and injuries.",
                "skills": ["Empathy", "Science", "Communication", "Resilience", "Attention to detail"],
                "salary_range": "GHS 8,000 - 40,000/month",
                "growth_outlook": "Always in demand",
                "related_programme_names": ["Medicine", "Human Biology", "Biomedical Sciences"],
            },
            {
                "name": "Pharmacy",
                "description": "Prepare and dispense medications safely.",
                "skills": ["Chemistry", "Attention to detail", "Communication", "Ethics", "Knowledge of drugs"],
                "salary_range": "GHS 4,000 - 15,000/month",
                "growth_outlook": "Steady demand",
                "related_programme_names": ["Pharmacy", "Pharmaceutical Sciences"],
            },
            {
                "name": "Nursing & Midwifery",
                "description": "Provide direct patient care and health education.",
                "skills": ["Compassion", "Communication", "Physical stamina", "Teamwork", "Observation"],
                "salary_range": "GHS 3,500 - 12,000/month",
                "growth_outlook": "High demand in Ghana",
                "related_programme_names": ["Nursing", "Midwifery", "Community Health"],
            },
        ],
    },
    {
        "key": "business",
        "name": "Business & Finance",
        "description": "Careers in managing, leading, and growing organisations.",
        "keywords": ["business", "finance", "management", "entrepreneur", "marketing", "accounting", "trade", "commerce", "economics"],
        "icon": "FiBriefcase",
        "colour": "#22c55e",
        "assessment_weight": 1,
        "careers": [
            {
                "name": "Business Management",
                "description": "Plan, direct, and coordinate business operations.",
                "skills": ["Leadership", "Communication", "Strategic thinking", "Numeracy", "Decision-making"],
                "salary_range": "GHS 4,000 - 20,000/month",
                "growth_outlook": "Strong local demand",
                "related_programme_names": ["Business Administration", "Management", "Human Resource Management"],
            },
            {
                "name": "Finance & Accounting",
                "description": "Manage financial records and advise on financial health.",
                "skills": ["Numeracy", "Analytical thinking", "Ethics", "Attention to detail", "Integrity"],
                "salary_range": "GHS 4,500 - 22,000/month",
                "growth_outlook": "Consistent demand",
                "related_programme_names": ["Accounting", "Finance", "Banking and Finance"],
            },
            {
                "name": "Marketing & Digital Media",
                "description": "Promote products and build brand awareness.",
                "skills": ["Creativity", "Communication", "Data analysis", "Persuasion", "Digital literacy"],
                "salary_range": "GHS 3,000 - 18,000/month",
                "growth_outlook": "Growing with digital economy",
                "related_programme_names": ["Marketing", "Public Relations", "Digital Media"],
            },
        ],
    },
    {
        "key": "education",
        "name": "Education & Training",
        "description": "Careers in teaching, training, and educational development.",
        "keywords": ["education", "teaching", "language", "history", "literature", "culture", "humanities", "training", "mentoring"],
        "icon": "FiBookOpen",
        "colour": "#8b5cf6",
        "assessment_weight": 1,
        "careers": [
            {
                "name": "Teaching & Education",
                "description": "Educate and inspire the next generation.",
                "skills": ["Communication", "Patience", "Creativity", "Organization", "Empathy"],
                "salary_range": "GHS 2,500 - 10,000/month",
                "growth_outlook": "Consistent national need",
                "related_programme_names": ["Education", "Education - Science", "Education - Arts", "Early Childhood Education"],
            },
            {
                "name": "Educational Leadership",
                "description": "Lead educational institutions and shape policy.",
                "skills": ["Leadership", "Communication", "Strategic planning", "Administration"],
                "salary_range": "GHS 5,000 - 15,000/month",
                "growth_outlook": "Growing demand",
                "related_programme_names": ["Education", "Educational Administration"],
            },
        ],
    },
    {
        "key": "law",
        "name": "Law & Public Policy",
        "description": "Careers in legal practice, governance, and public service.",
        "keywords": ["law", "legal", "social", "policy", "governance", "justice", "rights", "politics", "advocacy"],
        "icon": "FiUsers",
        "colour": "#6366f1",
        "assessment_weight": 1,
        "careers": [
            {
                "name": "Law (Legal Practice)",
                "description": "Advise clients and represent them in legal matters.",
                "skills": ["Analytical thinking", "Communication", "Research", "Ethics", "Persuasion"],
                "salary_range": "GHS 5,000 - 30,000/month",
                "growth_outlook": "Strong demand",
                "related_programme_names": ["Law", "LLB", "Legal Studies"],
            },
            {
                "name": "Public Administration",
                "description": "Manage government programmes and public services.",
                "skills": ["Leadership", "Communication", "Policy analysis", "Administration"],
                "salary_range": "GHS 3,500 - 15,000/month",
                "growth_outlook": "Government demand",
                "related_programme_names": ["Public Administration", "Political Science", "Governance"],
            },
        ],
    },
    {
        "key": "science",
        "name": "Science & Research",
        "description": "Careers in scientific research, laboratory work, and discovery.",
        "keywords": ["science", "research", "laboratory", "experiment", "analysis", "discovery", "physics", "chemistry", "biology"],
        "icon": "FiDatabase",
        "colour": "#14b8a6",
        "assessment_weight": 1,
        "careers": [
            {
                "name": "Research Scientist",
                "description": "Conduct scientific research to advance knowledge.",
                "skills": ["Critical thinking", "Research methodology", "Data analysis", "Writing", "Patience"],
                "salary_range": "GHS 4,000 - 18,000/month",
                "growth_outlook": "Growing with research investment",
                "related_programme_names": ["Physics", "Chemistry", "Biology", "Mathematics", "Environmental Science"],
            },
            {
                "name": "Laboratory Technician",
                "description": "Conduct laboratory tests and analyses.",
                "skills": ["Attention to detail", "Technical skills", "Accuracy", "Safety awareness"],
                "salary_range": "GHS 3,000 - 10,000/month",
                "growth_outlook": "Steady demand",
                "related_programme_names": ["Laboratory Technology", "Biomedical Sciences"],
            },
        ],
    },
    {
        "key": "environment",
        "name": "Environment & Sustainability",
        "description": "Careers in environmental protection, agriculture, and sustainability.",
        "keywords": ["environment", "sustainability", "agriculture", "farming", "nature", "food", "conservation", "ecology", "climate"],
        "icon": "FiMap",
        "colour": "#10b981",
        "assessment_weight": 1,
        "careers": [
            {
                "name": "Agricultural Science",
                "description": "Improve crop production and farming methods.",
                "skills": ["Science", "Practical skills", "Problem-solving", "Environmental awareness"],
                "salary_range": "GHS 3,000 - 15,000/month",
                "growth_outlook": "Key sector for Ghana's economy",
                "related_programme_names": ["Agriculture", "Agricultural Science", "Agricultural Engineering"],
            },
            {
                "name": "Environmental Science",
                "description": "Protect and manage natural resources.",
                "skills": ["Science", "Research", "Data analysis", "Communication", "Advocacy"],
                "salary_range": "GHS 3,500 - 14,000/month",
                "growth_outlook": "Growing environmental focus",
                "related_programme_names": ["Environmental Science", "Natural Resource Management", "Environmental Engineering"],
            },
        ],
    },
    {
        "key": "creative",
        "name": "Creative & Media",
        "description": "Careers in arts, design, media, and creative expression.",
        "keywords": ["creative", "media", "design", "art", "music", "film", "photography", "writing", "journalism", "content"],
        "icon": "FiPenTool",
        "colour": "#ec4899",
        "assessment_weight": 1,
        "careers": [
            {
                "name": "Graphic Design & Visual Communication",
                "description": "Create visual content for communication and marketing.",
                "skills": ["Creativity", "Design software", "Typography", "Colour theory", "Communication"],
                "salary_range": "GHS 3,000 - 15,000/month",
                "growth_outlook": "Growing with digital media",
                "related_programme_names": ["Graphic Design", "Visual Communication", "Fine Arts"],
            },
            {
                "name": "Journalism & Media",
                "description": "Inform the public through various media channels.",
                "skills": ["Writing", "Communication", "Research", "Creativity", "Ethics"],
                "salary_range": "GHS 2,500 - 12,000/month",
                "growth_outlook": "Digital media expansion",
                "related_programme_names": ["Journalism", "Media Studies", "Communication Studies"],
            },
        ],
    },
    {
        "key": "social",
        "name": "Social & Community Services",
        "description": "Careers in social work, community development, and humanitarian services.",
        "keywords": ["social", "community", "humanitarian", "development", "welfare", "counselling", "ngo", "volunteer"],
        "icon": "FiGlobe",
        "colour": "#f97316",
        "assessment_weight": 1,
        "careers": [
            {
                "name": "Social Work & Community Development",
                "description": "Support communities and vulnerable populations.",
                "skills": ["Empathy", "Communication", "Problem-solving", "Cultural awareness", "Advocacy"],
                "salary_range": "GHS 2,500 - 10,000/month",
                "growth_outlook": "Growing NGO sector",
                "related_programme_names": ["Social Work", "Community Development", "Social Sciences"],
            },
            {
                "name": "Counselling & Psychology",
                "description": "Help individuals with mental health and personal challenges.",
                "skills": ["Empathy", "Active listening", "Communication", "Patience", "Ethics"],
                "salary_range": "GHS 3,000 - 12,000/month",
                "growth_outlook": "Growing awareness",
                "related_programme_names": ["Psychology", "Counselling", "Social Work"],
            },
        ],
    },
]
